### ISSUE TITLE
issues regarding sheet layout

### ISSUE THREAD

**Issue by cateland** [LeonardoFacchin/Forbidden-Lands-System-FVTT#3]
The same issue that can be found on Firefox and safari can also be found on Chrome and Edge for macOS

Tested on chrome 84 on windows 10 ✅ 
Tested on chrome 84 on macOS Catalina 🚫 

I will try to look into it and hope to provide a PR

looks like an issue with `min-height: fit-content` applied to sheet section elements but a strange one.

**Comment by LeonardoFacchin** [comment]
Hello, thanks for the report.

Yes, I noticed the issue a few days ago and it seems persistent. In the end I decided to go with fixed heights for those elements and with

height: auto !important;
width: auto !important;

for all the core Foundry sheet containers in the hope that they will finally adapt to their content. Apparently they were set at the inline level by JS and overriding them was hard.
Hope this will make the sheet behavior more consistent across different browsers.

The update is not uploaded yet, since it contains a lot of small other changes and I want to try to fix all the bugs I can before uploading.
